let num1 = parseInt(prompt("Enter the first number: "))
let num2 = parseInt(prompt("Enter the second number: "))
let num3 = parseInt(prompt("Enter the third number: "))
let num4 = parseInt(prompt("Enter the fourth number: "))
let num5 = parseInt(prompt("Enter the fifth number: "))
